# Use wildcard "*" to expose all endpoints
# Can also expose individual endpoints with a comma-delimited list
#management.endpoints.web.exposure.include=*
#management.info.env.enabled = true

# Exclude individual endpoints with a comma-delimited list
#management.endpoints.web.exposure.exclude=health,info

#info.app.name = My Super Cool ironman App
#info.app.description= A crazy fun app, voohoo!
#info.app.version=1.0.0


#
# Define my properties
#

coach.name = Milan Mandal
team.name = MJ


#
# Change Spring boot embedded server port
#
#server.port=1234

#
# set the context path of the application
#

#server.servlet.context-path= /springbootOverview
#spring.main.lazy-initialization=true

